In [2]:
import numpy as np

<img src="img.png">

In [3]:
# np.random.rand(Принимающий, отдающий)
#
wih = np.random.rand(5, 2)

In [4]:
wih

array([[ 0.31160276,  0.26335614],
       [ 0.88117404,  0.86411833],
       [ 0.73283188,  0.82707012],
       [ 0.12645887,  0.50400642],
       [ 0.76452095,  0.32603236]])

In [5]:
who = np.random.rand(2, 5)

In [6]:
who

array([[ 0.57341892,  0.92716501,  0.52092447,  0.37691588,  0.79102033],
       [ 0.0954275 ,  0.09720801,  0.66652143,  0.10618895,  0.6945082 ]])

In [10]:
x = np.array([0.5, 0.3], ndmin=2).T
af = lambda x: 1 / (1 + np.exp(-x))

In [12]:
hidden_i = np.dot(wih, x)
print(hidden_i)
hidden_o = af(hidden_i)
print(hidden_o)


[[ 0.23480822]
 [ 0.69982252]
 [ 0.61453697]
 [ 0.21443136]
 [ 0.48007018]]
[[ 0.55843382]
 [ 0.66814842]
 [ 0.64897505]
 [ 0.55340337]
 [ 0.61776445]]


In [14]:
final_i = np.dot(who, hidden_o)
print(final_i)
final_o = af(final_i)
print(final_o)

[[ 1.97501809]
 [ 1.03860291]]
[[ 0.87814909]
 [ 0.73858035]]
